# Generated by Django 3.2.6 on 2025-04-04 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMedico',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JuntaMedica',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('resumen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfesionalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_medico', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaDiagnostica',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('resultados_preliminares', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('registro_medico', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('eventomedico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_medica.eventomedico')),
                ('tipo', models.CharField(max_length=100)),
                ('riesgos', models.TextField()),
            ],
            bases=('gestion_medica.eventomedico',),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('eventomedico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_medica.eventomedico')),
                ('motivo_consulta', models.TextField()),
                ('diagnostico_preliminar', models.TextField()),
                ('examenes_requeridos', models.TextField()),
                ('observaciones', models.TextField()),
            ],
            bases=('gestion_medica.eventomedico',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('profesionalsalud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_medica.profesionalsalud')),
                ('especialidad', models.CharField(max_length=100)),
                ('consultorio', models.IntegerField()),
            ],
            bases=('gestion_medica.profesionalsalud',),
        ),
        migrations.CreateModel(
            name='EEG',
            fields=[
                ('pruebadiagnostica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_medica.pruebadiagnostica')),
                ('archivo_eeg', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('eventos_detectados', models.TextField()),
            ],
            bases=('gestion_medica.pruebadiagnostica',),
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('profesionalsalud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_medica.profesionalsalud')),
                ('area_responsable', models.CharField(max_length=100)),
            ],
            bases=('gestion_medica.profesionalsalud',),
        ),
        migrations.CreateModel(
            name='MicroRNA',
            fields=[
                ('pruebadiagnostica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_medica.pruebadiagnostica')),
                ('biomarcadores', models.TextField()),
                ('nivel_expresion', models.IntegerField()),
            ],
            bases=('gestion_medica.pruebadiagnostica',),
        ),
        migrations.CreateModel(
            name='MRI',
            fields=[
                ('pruebadiagnostica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_medica.pruebadiagnostica')),
                ('archivo_dicom', models.CharField(max_length=255)),
                ('hallazgos_preliminares', models.TextField()),
            ],
            bases=('gestion_medica.pruebadiagnostica',),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('profesionalsalud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_medica.profesionalsalud')),
                ('tipo_examen', models.CharField(max_length=100)),
            ],
            bases=('gestion_medica.profesionalsalud',),
        ),
        migrations.AddField(
            model_name='profesionalsalud',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_medica.usuario'),
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.TextField()),
                ('dosis', models.TextField()),
                ('evento_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_medica.eventomedico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('numero_telefonico', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_medica.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InformeDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField()),
                ('junta_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_medica.juntamedica')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_sangre', models.CharField(max_length=10)),
                ('alergias_medicamentos', models.TextField()),
                ('condiciones_medicas', models.TextField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_medica.paciente')),
            ],
        ),
    ]
